# 服务端口
server:
  port: 80

  # 服务名
spring:
  application:
    name: server-gateway

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    #使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 设置路由id
        - id: service-hosp
        # 设置路由uri
          uri: lb://service-hosp
        # 设置路由断言，代理servicerId为auth-service的/auth/路径
          predicates: Path=/*/hosp/**

        # 设置路由id
        - id: service-cmn
          # 设置路由uri
          uri: lb://service-cmn
          # 设置路由断言，代理servicerId为auth-service的/auth/路径
          predicates: Path=/*/cmn/**

        - id: service-user
          uri: lb://service-user
          predicates: Path=/*/user/**

        - id: service-msm
          uri: lb://service-msm
          predicates: Path=/*/msm/**

        - id: service-user
          uri: lb://service-user
          predicates: Path=/*/ucenter/**
