server:
  port: 8160
spring:
  application:
    name: service-user
  profiles:
    active: dev

  datasource:
    username: root
    password: 7856915061
    url: jdbc:mysql://127.0.0.1:3306/hospital_user?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath:com/chong/user/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    redirect_url: http://localhost:8160/api/ucenter/wx/callback
    baseUrl: http://localhost:3000

