server:
  port: 8204
spring:
  application:
    name: service-msm

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    timeout: 180000
    lettuce:
      pool:
        min-idle: 0
        max-idle: 5
        max-wait: -1
        max-active: 20

        # nacos服务注册
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

aliyun:
  sms:
    regionId: default
    accessKeyId: LTAI5t8PfUA6NixrN7JoMquA
    secret: rVKefcD6z8RTZdXwzULtXE6gf94cmc

